name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test:
    runs-on: ubuntu-latest
    outputs:
      use-runner: ${{ steps.test-action.outputs.use-runner }}
    steps:
      - uses: actions/checkout@v4.1.1
      - id: test-action
        uses: ./
        with:
          primary-runner: 'ubuntu-latest'
          fallback-runner: 'windows-latest'
          github-token: ${{ secrets.TEST_GITHUB_TOKEN }}
      - name: Check output
        run: echo "Runner to use is ${{ steps.test-action.outputs.use-runner }}"

  test-output:
    needs: test
    runs-on: ${{ fromJson(needs.test.outputs.use-runner )}}
    steps:
      - name: Do something
        run: echo "Doing something on ${{ needs.test.outputs.use-runner }}"
      - name: Verify runner
        run: |
          if [[ "$(uname)" == "Linux" ]]; then
            echo "This is a Linux runner, likely ubuntu-latest."
          else
            echo "This is not a Linux runner."
            exit 1
          fi

  test-multiple-labels:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    outputs:
      use-runner: ${{ steps.test-action.outputs.use-runner }}
    steps:
      - uses: actions/checkout@v4.1.1
      - id: test-action
        uses: ./
        with:
          primary-runner: 'self-hosted,linux'
          fallback-runner: 'linux,x64'
          github-token: ${{ secrets.TEST_GITHUB_TOKEN }}
      - name: Check output
        run: echo "Runner to use is ${{ steps.test-action.outputs.use-runner }}"
